name: Do Not Merge

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  DoNotMerge:
    if: ${{ contains(github.event.*.labels.*.name, 'Do Not Merge') }}
    name: Do not merge
    runs-on: ubuntu-latest
    steps:
      - name: Check for do not merge label
        run: |
          echo "Pull request is labeled as 'Do Not Merge'"
          echo "Please do not merge this PR until you verify that it is good to be merged"
          exit 1